// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/infrastructure/db/tenant.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/tuannguyenandpadcojp/go-training/lqm/week7/day1/internal/domain"
)

// MockTenantDB is a mock of TenantDB interface.
type MockTenantDB struct {
	ctrl     *gomock.Controller
	recorder *MockTenantDBMockRecorder
}

// MockTenantDBMockRecorder is the mock recorder for MockTenantDB.
type MockTenantDBMockRecorder struct {
	mock *MockTenantDB
}

// NewMockTenantDB creates a new mock instance.
func NewMockTenantDB(ctrl *gomock.Controller) *MockTenantDB {
	mock := &MockTenantDB{ctrl: ctrl}
	mock.recorder = &MockTenantDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTenantDB) EXPECT() *MockTenantDBMockRecorder {
	return m.recorder
}

// GetTenantByID mocks base method.
func (m *MockTenantDB) GetTenantByID(ctx context.Context, id string) (*domain.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTenantByID", ctx, id)
	ret0, _ := ret[0].(*domain.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTenantByID indicates an expected call of GetTenantByID.
func (mr *MockTenantDBMockRecorder) GetTenantByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTenantByID", reflect.TypeOf((*MockTenantDB)(nil).GetTenantByID), ctx, id)
}
