// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: v1/tenant_service.proto

package tenantv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        *Tenant                `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantResponse) Reset() {
	*x = GetTenantResponse{}
	mi := &file_v1_tenant_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantResponse) ProtoMessage() {}

func (x *GetTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_tenant_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantResponse.ProtoReflect.Descriptor instead.
func (*GetTenantResponse) Descriptor() ([]byte, []int) {
	return file_v1_tenant_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetTenantResponse) GetTenant() *Tenant {
	if x != nil {
		return x.Tenant
	}
	return nil
}

type GetTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantRequest) Reset() {
	*x = GetTenantRequest{}
	mi := &file_v1_tenant_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantRequest) ProtoMessage() {}

func (x *GetTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_tenant_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantRequest.ProtoReflect.Descriptor instead.
func (*GetTenantRequest) Descriptor() ([]byte, []int) {
	return file_v1_tenant_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetTenantRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_v1_tenant_service_proto protoreflect.FileDescriptor

const file_v1_tenant_service_proto_rawDesc = "" +
	"\n" +
	"\x17v1/tenant_service.proto\x12\ttenant.v1\x1a\x0fv1/tenant.proto\">\n" +
	"\x11GetTenantResponse\x12)\n" +
	"\x06tenant\x18\x01 \x01(\v2\x11.tenant.v1.TenantR\x06tenant\"\"\n" +
	"\x10GetTenantRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2Y\n" +
	"\rTenantService\x12H\n" +
	"\tGetTenant\x12\x1b.tenant.v1.GetTenantRequest\x1a\x1c.tenant.v1.GetTenantResponse\"\x00BQZOgithub.com/tuannguyenandpadcojp/go-training/lqm/week7/day1/internal/pb;tenantv1b\x06proto3"

var (
	file_v1_tenant_service_proto_rawDescOnce sync.Once
	file_v1_tenant_service_proto_rawDescData []byte
)

func file_v1_tenant_service_proto_rawDescGZIP() []byte {
	file_v1_tenant_service_proto_rawDescOnce.Do(func() {
		file_v1_tenant_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_tenant_service_proto_rawDesc), len(file_v1_tenant_service_proto_rawDesc)))
	})
	return file_v1_tenant_service_proto_rawDescData
}

var file_v1_tenant_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_tenant_service_proto_goTypes = []any{
	(*GetTenantResponse)(nil), // 0: tenant.v1.GetTenantResponse
	(*GetTenantRequest)(nil),  // 1: tenant.v1.GetTenantRequest
	(*Tenant)(nil),            // 2: tenant.v1.Tenant
}
var file_v1_tenant_service_proto_depIdxs = []int32{
	2, // 0: tenant.v1.GetTenantResponse.tenant:type_name -> tenant.v1.Tenant
	1, // 1: tenant.v1.TenantService.GetTenant:input_type -> tenant.v1.GetTenantRequest
	0, // 2: tenant.v1.TenantService.GetTenant:output_type -> tenant.v1.GetTenantResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_tenant_service_proto_init() }
func file_v1_tenant_service_proto_init() {
	if File_v1_tenant_service_proto != nil {
		return
	}
	file_v1_tenant_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_tenant_service_proto_rawDesc), len(file_v1_tenant_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_tenant_service_proto_goTypes,
		DependencyIndexes: file_v1_tenant_service_proto_depIdxs,
		MessageInfos:      file_v1_tenant_service_proto_msgTypes,
	}.Build()
	File_v1_tenant_service_proto = out.File
	file_v1_tenant_service_proto_goTypes = nil
	file_v1_tenant_service_proto_depIdxs = nil
}
